[package]
name = "pivot-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
lazy_static = "1.4.0"
paste = "1.0"
llvm-sys = "140"
add_symbol = { path = "./add_symbol" }
range_marco = { path = "./range_marco" }
nom_locate = "4.0.0"
[dependencies.nom]
version = "7"
features = ["alloc"]