apiVersion: v1
kind: Service
metadata:
  labels:
    app: apt-repo
  name: apt-repo
  namespace: lang
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    app: apt-repo
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apt-repo
  name: apt-repo
  namespace: lang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apt-repo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apt-repo
    spec:
      priorityClassName: high-priority
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/pivotstudio/lang-apt:{{.build_tag}}
          name: apt-repo
          ports:
            - containerPort: 8110
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always
status: {}

